GEN_DATA_FOLDER = "_gen"

IMAGE_DATA_FILE = "image-data.txt"
EXCEL_DATA_FILE = "students.xls"
MATCH_DATA_FILE = f"{GEN_DATA_FOLDER}/match.txt"
NO_GF_IMAGES_DATA_FILE = f"{GEN_DATA_FOLDER}/no-gf-images.txt"
NO_GF_STUDENTS_DATA_FILE = f"{GEN_DATA_FOLDER}/no-gf-students.txt"
NO_GF_DATA_FILE = f"{GEN_DATA_FOLDER}/no-gf.xlsx"
MATCHED_DATA_FILE = f"{GEN_DATA_FOLDER}/matched-data.xlsx"
NO_VECTORS_MATCHED_DATA_FILE = f"{GEN_DATA_FOLDER}/no-vectors-matched-data.xlsx"
